### ISSUE TITLE
“https://github.com/Fra-Tsuna/vlm-grasping” Page not found

### ISSUE THREAD

**Issue by wwwzxxzw** [Lab-RoCoCo-Sapienza/empower#1]
Hello, I can't find the project at https://github.com/Fra-Tsuna/vlm-grasping. Could you please provide it? Thank you!

**Comment by Fra-Tsuna** [comment]
Hi,
the repo link in the Readme is the old one, we completely moved everything inside this repo.
Thanks for pointing that out, we will immediately update that.

Please use the following git clone command

`git clone https://github.com/Lab-RoCoCo-Sapienza/empower.git`
