### ISSUE TITLE
error about “conda env create -f environment.yml”

### ISSUE THREAD

**Issue by wwwzxxzw** [Lab-RoCoCo-Sapienza/empower#2]
hello！
My system is Ubuntu 20.04 with ROS 1. When I run “conda env create -f environment.yml” according to the README, the following error occurs:
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 1.3.0 Requires-Python >=3.9; 2.10.1 Requires-Python <3; 2.11.0 Requires-Python <3; 2.11.1 Requires-Python <3; 2.4.0 Requires-Python <3; 2.4.1 Requires-Python <3; 2.4.2 Requires-Python <3; 2.4.3 Requires-Python <3; 2.4.4 Requires-Python <3; 2.5.0 Requires-Python <3; 2.5.1 Requires-Python <3; 2.5.2 Requires-Python <3; 2.6.0 Requires-Python <3; 2.6.1 Requires-Python <3; 2.6.2 Requires-Python <3; 2.7.0 Requires-Python <3; 2.7.2 Requires-Python <3; 2.8.0 Requires-Python <3; 2.8.1 Requires-Python <3; 2.8.2 Requires-Python <3; 2.8.3 Requires-Python <3; 2.8.4 Requires-Python <3; 2.8.5 Requires-Python <3; 2.8.6 Requires-Python <3; 2.8.7 Requires-Python <3; 2.9.2 Requires-Python <3; 4.6.0 Requires-Python >=3.9

ERROR: Could not find a version that satisfies the requirement en-core-web-sm==3.7.1 (from versions: none)
ERROR: No matching distribution found for en-core-web-sm==3.7.1

failed

CondaEnvException: Pip failed.

How can I resolve this? I would greatly appreciate any help you can provide!

**Comment by wwwzxxzw** [comment]
![image](https://github.com/user-attachments/assets/652278ba-cef4-4926-906e-50a15b3b6d11)
![image](https://github.com/user-attachments/assets/9b928351-5ce5-47e3-acc0-9711eda4c308)

**Comment by wwwzxxzw** [comment]
Additionally, the spawn_marker_centroids.py file mentioned in the README does not exist in the scr directory. Does this refer to either the spawn_clusters_points.py or spawn_objects.py file?

**Comment by michelebri** [comment]
Hello!
We’ve resolved the issue by cleaning up the old environment file. You can follow the updated README to install the environment properly. You can use spawn_clusters_points.py  to show the objects' points in the point cloud.
